# Generated by Django 5.2.5 on 2025-08-21 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_contactmessage_delete_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmessage',
            old_name='first_name',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='contactmessage',
            old_name='last_name',
            new_name='lastName',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='created_at',
        ),
    ]
