# Generated by Django 5.2.5 on 2025-08-21 15:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_first_name_contactmessage_firstname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmessage',
            old_name='firstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='contactmessage',
            old_name='lastName',
            new_name='last_name',
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
